markdown: kramdown
app_id: 1571831709779231
input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
hard_wrap: false
highlighter: rouge
exclude: ['README.md']
url: mellowviews.com
paginate: 12
paginate_path: "page:num"
gems:
  - jekyll-seo-tag
  - jekyll-paginate
