markdown: kramdown
input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
hard_wrap: false
highlighter: rouge
exclude: ['README.md']
url: mellowviews.com
gems: [jekyll-paginate]
paginate: 12
paginate_path: "page:num"
