markdown: kramdown
title: Mellow Views
input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
hard_wrap: false
highlighter: rouge
exclude: ['README.md']
url: mellowviews.com
paginate: 12
paginate_path: "page:num"
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
